swagger: '2.0'
info:
  description: Products store REST API Documentation
  version: '0.1'
  title: Products store REST API Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /

tags:
  - name: product-controller
    description: Product service API
  - name: order-controller
    description: Order service API

paths:
  /order:
    get:
      tags:
        - order-controller
      summary: getAll
      operationId: getAllUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/OrderDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    post:
      tags:
        - order-controller
      summary: create
      operationId: createUsingPOST
      consumes:
        - application/json;charset=UTF-8
      produces:
        - '*/*'
      parameters:
        - in: body
          name: orderDTO
          description: orderDTO
          required: true
          schema:
            $ref: '#/definitions/OrderDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/order/{id}':
    get:
      tags:
        - order-controller
      summary: getOrder
      operationId: getOrder
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OrderDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    put:
      tags:
        - order-controller
      summary: update
      operationId: updateOrder
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
        - in: body
          name: orderDTO
          description: orderDTO
          required: true
          schema:
            $ref: '#/definitions/OrderDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    delete:
      tags:
        - order-controller
      summary: delete
      operationId: deleteOrder
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /product:
    get:
      tags:
        - product-controller
      summary: getAll
      operationId: getAllProducts
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - product-controller
      summary: create
      operationId: createProduct
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: body
          name: productDTO
          description: productDTO
          required: true
          schema:
            $ref: '#/definitions/ProductDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/product/{id}':
    get:
      tags:
        - product-controller
      summary: getProduct
      operationId: getProductUsingGET
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProductDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    put:
      tags:
        - product-controller
      summary: update
      operationId: updateProduct
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
        - in: body
          name: productDTO
          description: productDTO
          required: true
          schema:
            $ref: '#/definitions/ProductDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    delete:
      tags:
        - product-controller
      summary: delete
      operationId: deleteProduct
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'

        '401':
          description: Unauthorized
        '403':
          description: Forbidden

definitions:
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - '200'
          - '400'
          - '401'
          - '404'

      statusCodeValue:
        type: integer
        format: int32

  OrderDTO:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: '#/definitions/ProductDTO'
      totalPrice:
        type: number
        format: double

  ProductDTO:
    type: object
    properties:
      id:
        type: integer
        format: int32
      price:
        type: number
        format: double
      productName:
        type: string